// Mock data for credit cards
export const mockCards = [
  {
    id: "hdfc_regalia",
    name: "Regalia Credit Card",
    bank: "HDFC Bank",
    network: "Visa",
    type: "Premium",
    annualFee: 2500,
    joiningFee: 1000,
    addOnCardFee: 0,
    foreignTransactionFee: 3.5,
    interestRate: 3.49,
    cashAdvanceFee: 2.5,
    latePaymentFee: 750,
    overLimitFee: 600,
    rewardsRate: 4,
    cashbackRate: 1.5,
    minIncome: 1200000,
    minCreditScore: 750,
    ageRequirement: "21-60 years",
    documentsRequired: ["PAN Card", "Aadhaar Card", "Income Proof"],
    summary: "Premium travel card with complimentary lounge access and milestone benefits",
    aiSummary:
      "The HDFC Regalia is a premium travel credit card offering excellent rewards on travel and dining. With complimentary airport lounge access, milestone benefits, and comprehensive insurance coverage, it's ideal for frequent travelers with moderate to high spending habits. The annual fee is often waived based on spending thresholds, making it a cost-effective option for regular users.",
    tags: ["Travel", "Dining", "Premium", "Lounge Access", "Insurance"],
    benefits: [
      "Complimentary airport lounge access (domestic and international)",
      "4X reward points on all spends",
      "1 reward point = ₹0.30",
      "Annual fee waiver on spending ₹3,00,000 in a year",
      "Milestone benefits of 10,000 bonus points on spending ₹5,00,000",
      "Golf privileges at select courses",
      "Comprehensive travel and purchase protection insurance",
      "24/7 concierge services",
    ],
    rewardsStructure: [
      "4X reward points on all retail spends",
      "10X reward points on HDFC SmartBuy portal",
      "2X reward points on international transactions",
      "5X reward points on weekend dining",
    ],
    welcomeOffers: [
      "10,000 bonus reward points on spending ₹1,00,000 within 60 days",
      "BookMyShow vouchers worth ₹1,000",
      "Amazon e-gift voucher worth ₹1,000",
    ],
    feeWaiverConditions: [
      "Annual fee waiver on spending ₹3,00,000 in the previous year",
      "50% fee waiver on spending ₹2,00,000 in the previous year",
    ],
    rating: 4.5,
    reviews: 1245,
    loungeAccess: true,
    fuelSurchargeWaiver: true,
    movieBenefits: true,
    diningBenefits: true,
    welcomeBonus: "10,000 reward points",
  },
  {
    id: "axis_magnus",
    name: "Magnus Credit Card",
    bank: "Axis Bank",
    network: "Visa",
    type: "Super Premium",
    annualFee: 10000,
    joiningFee: 5000,
    addOnCardFee: 0,
    foreignTransactionFee: 2,
    interestRate: 3.4,
    cashAdvanceFee: 2.5,
    latePaymentFee: 1000,
    overLimitFee: 800,
    rewardsRate: 5,
    cashbackRate: 2,
    minIncome: 1800000,
    minCreditScore: 780,
    ageRequirement: "21-65 years",
    documentsRequired: ["PAN Card", "Aadhaar Card", "Income Proof", "Address Proof"],
    summary: "Super premium lifestyle card with exclusive privileges and high reward rates",
    aiSummary:
      "The Axis Magnus is a super-premium credit card designed for affluent customers seeking exclusive lifestyle benefits. It offers one of the highest reward rates in the market at 5X points, unlimited airport lounge access worldwide, and premium concierge services. While the annual fee is high, the extensive benefits and milestone rewards make it worthwhile for high spenders who value luxury travel and dining experiences.",
    tags: ["Super Premium", "Travel", "Lifestyle", "Luxury", "Unlimited Lounge Access"],
    benefits: [
      "Unlimited airport lounge access worldwide",
      "5X reward points on all spends",
      "1 reward point = ₹0.40",
      "Complimentary Taj Epicure Plus membership",
      "Complimentary Club Marriott membership",
      "Golf privileges at over 100 courses worldwide",
      "Premium concierge services",
      "Comprehensive travel insurance up to ₹50,00,000",
      "Milestone benefits of 25,000 bonus points on spending ₹10,00,000",
    ],
    rewardsStructure: [
      "5X reward points on all retail spends",
      "10X reward points on travel bookings through Axis Travel Portal",
      "8X reward points on international transactions",
      "15X reward points on luxury brand purchases",
    ],
    welcomeOffers: [
      "50,000 bonus reward points on spending ₹2,00,000 within 90 days",
      "Complimentary stay at select 5-star hotels",
      "Amazon e-gift voucher worth ₹5,000",
    ],
    feeWaiverConditions: [
      "Annual fee waiver on spending ₹15,00,000 in the previous year",
      "50% fee waiver on spending ₹10,00,000 in the previous year",
    ],
    rating: 4.7,
    reviews: 856,
    loungeAccess: true,
    fuelSurchargeWaiver: true,
    movieBenefits: true,
    diningBenefits: true,
    welcomeBonus: "50,000 reward points",
  },
  {
    id: "icici_emeralde",
    name: "Emeralde Credit Card",
    bank: "ICICI Bank",
    network: "Mastercard",
    type: "Premium",
    annualFee: 3000,
    joiningFee: 2000,
    addOnCardFee: 0,
    foreignTransactionFee: 3,
    interestRate: 3.5,
    cashAdvanceFee: 2.5,
    latePaymentFee: 800,
    overLimitFee: 600,
    rewardsRate: 3,
    cashbackRate: 1.5,
    minIncome: 1000000,
    minCreditScore: 740,
    ageRequirement: "21-60 years",
    documentsRequired: ["PAN Card", "Aadhaar Card", "Income Proof"],
    summary: "Premium lifestyle card with strong dining and entertainment benefits",
    aiSummary:
      "The ICICI Emeralde is a premium lifestyle credit card that excels in dining and entertainment benefits. It offers 3X reward points on all spends with accelerated rewards for dining, movies, and online shopping. The card provides complimentary domestic lounge access, movie ticket discounts, and dining privileges at partner restaurants. With a moderate annual fee that can be waived based on spending, it's an excellent choice for urban professionals who enjoy dining out and entertainment.",
    tags: ["Lifestyle", "Dining", "Entertainment", "Shopping", "Premium"],
    benefits: [
      "Complimentary domestic airport lounge access (8 visits per year)",
      "3X reward points on all spends",
      "1 reward point = ₹0.25",
      "Buy 1 Get 1 movie ticket on BookMyShow (up to 2 per month)",
      "15% discount at partner restaurants",
      "Annual fee waiver on spending ₹3,50,000 in a year",
      "Milestone benefits of 5,000 bonus points on spending ₹4,00,000",
      "Fuel surcharge waiver up to ₹500 per month",
    ],
    rewardsStructure: [
      "3X reward points on all retail spends",
      "5X reward points on dining transactions",
      "10X reward points on ICICI Bank's shopping portal",
      "2X reward points on utility bill payments",
    ],
    welcomeOffers: [
      "8,000 bonus reward points on spending ₹75,000 within 60 days",
      "BookMyShow vouchers worth ₹1,500",
      "Complimentary Zomato Pro membership for 1 year",
    ],
    feeWaiverConditions: [
      "Annual fee waiver on spending ₹3,50,000 in the previous year",
      "50% fee waiver on spending ₹2,50,000 in the previous year",
    ],
    rating: 4.3,
    reviews: 1089,
    loungeAccess: true,
    fuelSurchargeWaiver: true,
    movieBenefits: true,
    diningBenefits: true,
    welcomeBonus: "8,000 reward points",
  },
  {
    id: "sbi_elite",
    name: "Elite Credit Card",
    bank: "SBI Card",
    network: "Visa",
    type: "Premium",
    annualFee: 4999,
    joiningFee: 4999,
    addOnCardFee: 0,
    foreignTransactionFee: 3.5,
    interestRate: 3.35,
    cashAdvanceFee: 2.5,
    latePaymentFee: 750,
    overLimitFee: 600,
    rewardsRate: 5,
    cashbackRate: 1.25,
    minIncome: 1500000,
    minCreditScore: 760,
    ageRequirement: "21-65 years",
    documentsRequired: ["PAN Card", "Aadhaar Card", "Income Proof"],
    summary: "Premium travel and lifestyle card with high reward points and milestone benefits",
    aiSummary:
      "The SBI Elite is a premium credit card offering exceptional value for frequent travelers and high spenders. With 5X reward points on all purchases, complimentary domestic and international lounge access, and comprehensive travel insurance, it's designed for those who travel regularly. The card also features strong milestone benefits, including bonus points and e-vouchers. While the annual fee is on the higher side, it can be offset by the generous welcome offers and spending-based fee waivers.",
    tags: ["Travel", "Premium", "Rewards", "Lounge Access", "Insurance"],
    benefits: [
      "Complimentary airport lounge access (domestic: 8 visits, international: 6 visits per year)",
      "5X reward points on all spends",
      "1 reward point = ₹0.25",
      "Annual fee waiver on spending ₹6,00,000 in a year",
      "Milestone benefits: e-vouchers worth ₹5,000 on spending ₹6,00,000",
      "Comprehensive travel insurance up to ₹50,00,000",
      "Fuel surcharge waiver up to ₹1,000 per month",
      "24/7 concierge services",
    ],
    rewardsStructure: [
      "5X reward points on all retail spends",
      "10X reward points on dining and entertainment",
      "5X reward points on international transactions",
      "2X reward points on utility bill payments",
    ],
    welcomeOffers: [
      "20,000 bonus reward points on spending ₹1,50,000 within 90 days",
      "Amazon e-gift voucher worth ₹3,000",
      "Complimentary movie tickets worth ₹1,000",
    ],
    feeWaiverConditions: [
      "Annual fee waiver on spending ₹6,00,000 in the previous year",
      "50% fee waiver on spending ₹4,00,000 in the previous year",
    ],
    rating: 4.4,
    reviews: 978,
    loungeAccess: true,
    fuelSurchargeWaiver: true,
    movieBenefits: true,
    diningBenefits: true,
    welcomeBonus: "20,000 reward points",
  },
  {
    id: "amex_platinum",
    name: "Platinum Reserve Card",
    bank: "American Express",
    network: "American Express",
    type: "Super Premium",
    annualFee: 5000,
    joiningFee: 5000,
    addOnCardFee: 1500,
    foreignTransactionFee: 3.5,
    interestRate: 3.25,
    cashAdvanceFee: 2.5,
    latePaymentFee: 800,
    overLimitFee: 600,
    rewardsRate: 4,
    cashbackRate: 1.75,
    minIncome: 1800000,
    minCreditScore: 770,
    ageRequirement: "21-65 years",
    documentsRequired: ["PAN Card", "Aadhaar Card", "Income Proof", "Address Proof"],
    summary: "Premium lifestyle card with exclusive dining and travel privileges",
    aiSummary:
      "The American Express Platinum Reserve is a premium lifestyle card that excels in dining and travel benefits. It offers 4X reward points with exceptional redemption value, complimentary domestic and international lounge access, and exclusive dining privileges through the Amex Dining Program. The card provides strong travel insurance coverage and premium concierge services. While the annual fee is moderate for its category, the extensive benefits and high-value welcome offers make it an excellent choice for those who frequently dine out and travel.",
    tags: ["Premium", "Dining", "Travel", "Lifestyle", "Concierge"],
    benefits: [
      "Complimentary airport lounge access (domestic and international)",
      "4X membership reward points on all spends",
      "1 membership reward point = ₹0.35",
      "Exclusive access to Amex Dining Program with up to 20% savings",
      "Annual fee waiver on spending ₹4,50,000 in a year",
      "Milestone benefits: 15,000 bonus points on spending ₹5,00,000",
      "Travel insurance coverage up to ₹40,00,000",
      "Premium concierge services",
      "Taj Epicure membership with up to 25% savings on dining",
    ],
    rewardsStructure: [
      "4X membership reward points on all retail spends",
      "8X membership reward points on dining transactions",
      "5X membership reward points on travel bookings",
      "2X membership reward points on utility bill payments",
    ],
    welcomeOffers: [
      "15,000 bonus membership reward points on spending ₹1,25,000 within 90 days",
      "Taj voucher worth ₹10,000",
      "Complimentary weekend stay at select Taj properties",
    ],
    feeWaiverConditions: [
      "Annual fee waiver on spending ₹4,50,000 in the previous year",
      "50% fee waiver on spending ₹3,00,000 in the previous year",
    ],
    rating: 4.6,
    reviews: 765,
    loungeAccess: true,
    fuelSurchargeWaiver: false,
    movieBenefits: false,
    diningBenefits: true,
    welcomeBonus: "15,000 membership reward points",
  },
  {
    id: "yes_preferred",
    name: "Preferred Credit Card",
    bank: "YES Bank",
    network: "Mastercard",
    type: "Premium",
    annualFee: 999,
    joiningFee: 999,
    addOnCardFee: 0,
    foreignTransactionFee: 3.5,
    interestRate: 3.6,
    cashAdvanceFee: 2.5,
    latePaymentFee: 700,
    overLimitFee: 500,
    rewardsRate: 2,
    cashbackRate: 1,
    minIncome: 600000,
    minCreditScore: 720,
    ageRequirement: "21-60 years",
    documentsRequired: ["PAN Card", "Aadhaar Card", "Income Proof"],
    summary: "Value-focused card with strong fuel and utility bill benefits",
    aiSummary:
      "The YES Bank Preferred Credit Card is a value-focused option with a low annual fee and strong benefits for everyday spending. It offers 2X reward points on all purchases with accelerated rewards for fuel and utility bill payments. The card provides fuel surcharge waivers, complimentary domestic lounge access, and movie ticket discounts. With a low annual fee that's easily waived, it's an excellent entry-level premium card for young professionals looking for everyday value without a high income requirement.",
    tags: ["Value", "Fuel", "Utility Bills", "Movies", "Entry Premium"],
    benefits: [
      "Complimentary domestic airport lounge access (4 visits per year)",
      "2X reward points on all spends",
      "1 reward point = ₹0.25",
      "Fuel surcharge waiver up to ₹400 per month",
      "10% cashback on utility bill payments (up to ₹100 per month)",
      "Buy 1 Get 1 movie ticket on BookMyShow (up to 1 per month)",
      "Annual fee waiver on spending ₹1,50,000 in a year",
    ],
    rewardsStructure: [
      "2X reward points on all retail spends",
      "5X reward points on fuel transactions",
      "3X reward points on utility bill payments",
      "4X reward points on grocery purchases",
    ],
    welcomeOffers: [
      "2,500 bonus reward points on spending ₹25,000 within 60 days",
      "BookMyShow vouchers worth ₹500",
      "Fuel voucher worth ₹500",
    ],
    feeWaiverConditions: [
      "Annual fee waiver on spending ₹1,50,000 in the previous year",
      "50% fee waiver on spending ₹1,00,000 in the previous year",
    ],
    rating: 4.1,
    reviews: 1234,
    loungeAccess: true,
    fuelSurchargeWaiver: true,
    movieBenefits: true,
    diningBenefits: false,
    welcomeBonus: "2,500 reward points",
  },
  {
    id: "kotak_white",
    name: "White Credit Card",
    bank: "Kotak Mahindra Bank",
    network: "Visa",
    type: "Premium",
    annualFee: 999,
    joiningFee: 999,
    addOnCardFee: 0,
    foreignTransactionFee: 3.5,
    interestRate: 3.49,
    cashAdvanceFee: 2.5,
    latePaymentFee: 750,
    overLimitFee: 500,
    rewardsRate: 3,
    cashbackRate: 1.5,
    minIncome: 800000,
    minCreditScore: 730,
    ageRequirement: "21-60 years",
    documentsRequired: ["PAN Card", "Aadhaar Card", "Income Proof"],
    summary: "Lifestyle card with strong online shopping and entertainment benefits",
    aiSummary:
      "The Kotak White Credit Card is a lifestyle-focused card that excels in online shopping and entertainment benefits. It offers 3X reward points on all purchases with accelerated rewards for online transactions and entertainment. The card provides complimentary domestic lounge access, movie ticket discounts, and special offers on popular e-commerce platforms. With a low annual fee and easy waiver conditions, it's perfect for young professionals who shop online frequently and enjoy entertainment benefits.",
    tags: ["Lifestyle", "Online Shopping", "Entertainment", "Movies", "E-commerce"],
    benefits: [
      "Complimentary domestic airport lounge access (6 visits per year)",
      "3X reward points on all spends",
      "1 reward point = ₹0.30",
      "5X reward points on online shopping",
      "Buy 1 Get 1 movie ticket on BookMyShow (up to 2 per month)",
      "10% discount on Zomato orders (up to ₹150 per month)",
      "Annual fee waiver on spending ₹1,80,000 in a year",
    ],
    rewardsStructure: [
      "3X reward points on all retail spends",
      "5X reward points on online shopping",
      "4X reward points on entertainment transactions",
      "2X reward points on utility bill payments",
    ],
    welcomeOffers: [
      "5,000 bonus reward points on spending ₹50,000 within 60 days",
      "Amazon e-gift voucher worth ₹1,000",
      "BookMyShow vouchers worth ₹1,000",
    ],
    feeWaiverConditions: [
      "Annual fee waiver on spending ₹1,80,000 in the previous year",
      "50% fee waiver on spending ₹1,20,000 in the previous year",
    ],
    rating: 4.2,
    reviews: 892,
    loungeAccess: true,
    fuelSurchargeWaiver: false,
    movieBenefits: true,
    diningBenefits: true,
    welcomeBonus: "5,000 reward points",
  },
  {
    id: "indusind_pinnacle",
    name: "Pinnacle Credit Card",
    bank: "IndusInd Bank",
    network: "Visa",
    type: "Super Premium",
    annualFee: 12000,
    joiningFee: 12000,
    addOnCardFee: 0,
    foreignTransactionFee: 2,
    interestRate: 3.35,
    cashAdvanceFee: 2.5,
    latePaymentFee: 1000,
    overLimitFee: 800,
    rewardsRate: 6,
    cashbackRate: 2.5,
    minIncome: 2500000,
    minCreditScore: 800,
    ageRequirement: "21-65 years",
    documentsRequired: ["PAN Card", "Aadhaar Card", "Income Proof", "Address Proof"],
    summary: "Ultra-premium card with highest reward rates and exclusive luxury benefits",
    aiSummary:
      "The IndusInd Pinnacle is an ultra-premium credit card offering the highest reward rates in the market at 6X points on all spends. It provides unlimited airport lounge access worldwide, exclusive luxury hotel partnerships, and premium concierge services. The card features comprehensive travel insurance, golf privileges at premium courses, and milestone benefits that can offset the high annual fee. Designed for ultra-high net worth individuals, it offers unparalleled luxury benefits and service quality.",
    tags: ["Ultra Premium", "Luxury", "Highest Rewards", "Unlimited Lounge", "Concierge"],
    benefits: [
      "Unlimited airport lounge access worldwide (including Priority Pass)",
      "6X reward points on all spends",
      "1 reward point = ₹0.50",
      "Complimentary ITC Hotels membership with exclusive benefits",
      "Golf privileges at over 150 courses worldwide",
      "Premium concierge services 24/7",
      "Comprehensive travel insurance up to ₹1,00,00,000",
      "Milestone benefits: 50,000 bonus points on spending ₹20,00,000",
      "Annual fee waiver on spending ₹25,00,000 in a year",
    ],
    rewardsStructure: [
      "6X reward points on all retail spends",
      "12X reward points on luxury brand purchases",
      "10X reward points on international transactions",
      "8X reward points on dining and travel",
    ],
    welcomeOffers: [
      "1,00,000 bonus reward points on spending ₹5,00,000 within 90 days",
      "Complimentary stay at ITC Hotels worth ₹25,000",
      "Amazon e-gift voucher worth ₹10,000",
    ],
    feeWaiverConditions: [
      "Annual fee waiver on spending ₹25,00,000 in the previous year",
      "50% fee waiver on spending ₹15,00,000 in the previous year",
    ],
    rating: 4.8,
    reviews: 456,
    loungeAccess: true,
    fuelSurchargeWaiver: true,
    movieBenefits: true,
    diningBenefits: true,
    welcomeBonus: "1,00,000 reward points",
  },
  {
    id: "standard_chartered_ultimate",
    name: "Ultimate Credit Card",
    bank: "Standard Chartered",
    network: "Mastercard",
    type: "Premium",
    annualFee: 3500,
    joiningFee: 3500,
    addOnCardFee: 0,
    foreignTransactionFee: 3,
    interestRate: 3.4,
    cashAdvanceFee: 2.5,
    latePaymentFee: 800,
    overLimitFee: 600,
    rewardsRate: 4,
    cashbackRate: 2,
    minIncome: 1200000,
    minCreditScore: 750,
    ageRequirement: "21-60 years",
    documentsRequired: ["PAN Card", "Aadhaar Card", "Income Proof"],
    summary: "Premium travel card with strong international benefits and cashback options",
    aiSummary:
      "The Standard Chartered Ultimate Credit Card is a premium travel-focused card offering excellent international benefits and flexible reward redemption options. It provides 4X reward points on all spends with the option to convert to cashback at attractive rates. The card features complimentary airport lounge access, comprehensive travel insurance, and special privileges for international transactions. With strong milestone benefits and fee waiver conditions, it's ideal for frequent international travelers who value flexibility in reward redemption.",
    tags: ["Travel", "International", "Cashback", "Premium", "Flexible Rewards"],
    benefits: [
      "Complimentary airport lounge access (domestic: 6 visits, international: 4 visits per year)",
      "4X reward points on all spends",
      "1 reward point = ₹0.30 or 2% cashback option",
      "No foreign transaction fees on international spends above $1000 per month",
      "Comprehensive travel insurance up to ₹50,00,000",
      "Annual fee waiver on spending ₹4,00,000 in a year",
      "Milestone benefits: 10,000 bonus points on spending ₹5,00,000",
      "24/7 global customer service",
    ],
    rewardsStructure: [
      "4X reward points on all retail spends",
      "6X reward points on international transactions",
      "5X reward points on travel bookings",
      "3X reward points on utility bill payments",
    ],
    welcomeOffers: [
      "12,000 bonus reward points on spending ₹1,00,000 within 60 days",
      "Travel voucher worth ₹2,500",
      "Complimentary Priority Pass membership for 1 year",
    ],
    feeWaiverConditions: [
      "Annual fee waiver on spending ₹4,00,000 in the previous year",
      "50% fee waiver on spending ₹2,50,000 in the previous year",
    ],
    rating: 4.4,
    reviews: 687,
    loungeAccess: true,
    fuelSurchargeWaiver: false,
    movieBenefits: false,
    diningBenefits: true,
    welcomeBonus: "12,000 reward points",
  },
  {
    id: "citi_prestige",
    name: "Prestige Credit Card",
    bank: "Citibank",
    network: "Visa",
    type: "Super Premium",
    annualFee: 20000,
    joiningFee: 20000,
    addOnCardFee: 0,
    foreignTransactionFee: 0,
    interestRate: 3.25,
    cashAdvanceFee: 2.5,
    latePaymentFee: 1200,
    overLimitFee: 1000,
    rewardsRate: 4,
    cashbackRate: 2,
    minIncome: 3600000,
    minCreditScore: 800,
    ageRequirement: "21-65 years",
    documentsRequired: ["PAN Card", "Aadhaar Card", "Income Proof", "Address Proof", "Bank Statements"],
    summary: "Ultra-premium card with no foreign transaction fees and exclusive global privileges",
    aiSummary:
      "The Citibank Prestige is an ultra-premium credit card designed for high-net-worth individuals who travel internationally frequently. It offers zero foreign transaction fees, unlimited airport lounge access worldwide, and exclusive privileges with luxury hotel chains. The card provides comprehensive travel insurance, premium concierge services, and access to exclusive events. While the annual fee is among the highest in the market, the extensive global benefits and high-value welcome offers make it worthwhile for affluent customers with significant international spending.",
    tags: ["Ultra Premium", "International", "No Foreign Fees", "Luxury", "Global Benefits"],
    benefits: [
      "Unlimited airport lounge access worldwide (including Priority Pass)",
      "4X reward points on all spends",
      "1 reward point = ₹0.40",
      "Zero foreign transaction fees",
      "Complimentary 4th night free at participating hotels worldwide",
      "Exclusive access to Citi Private Pass events",
      "Premium concierge services 24/7",
      "Comprehensive travel insurance up to ₹1,00,00,000",
      "Golf privileges at premium courses worldwide",
      "Annual fee waiver on spending ₹30,00,000 in a year",
    ],
    rewardsStructure: [
      "4X reward points on all retail spends",
      "8X reward points on travel and dining",
      "6X reward points on international transactions",
      "2X reward points on utility bill payments",
    ],
    welcomeOffers: [
      "1,50,000 bonus reward points on spending ₹8,00,000 within 90 days",
      "Complimentary hotel stay worth ₹50,000",
      "Amazon e-gift voucher worth ₹15,000",
    ],
    feeWaiverConditions: [
      "Annual fee waiver on spending ₹30,00,000 in the previous year",
      "50% fee waiver on spending ₹20,00,000 in the previous year",
    ],
    rating: 4.7,
    reviews: 234,
    loungeAccess: true,
    fuelSurchargeWaiver: false,
    movieBenefits: false,
    diningBenefits: true,
    welcomeBonus: "1,50,000 reward points",
  },
]
